name: export-secrets
on: workflow_dispatch
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Encrypt secrets
        env:
          APPLE_DEVELOPER_ID_APPLICATION_P12_BASE64: ${{ secrets.APPLE_DEVELOPER_ID_APPLICATION_P12_BASE64 }}
          APPLE_DEVELOPER_ID_APPLICATION_P12_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_APPLICATION_P12_PASSWORD }}
          APPLE_DEVELOPER_ID_INSTALLER_P12_BASE64: ${{ secrets.APPLE_DEVELOPER_ID_INSTALLER_P12_BASE64 }}
          APPLE_DEVELOPER_ID_INSTALLER_P12_PASSWORD: ${{ secrets.APPLE_DEVELOPER_ID_INSTALLER_P12_PASSWORD }}
          APPLE_NOTARY_ISSUER_ID: ${{ secrets.APPLE_NOTARY_ISSUER_ID }}
          APPLE_NOTARY_KEY_ID: ${{ secrets.APPLE_NOTARY_KEY_ID }}
          APPLE_NOTARY_KEY_P8_BASE64: ${{ secrets.APPLE_NOTARY_KEY_P8_BASE64 }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          sudo apt-get install -y age >/dev/null
          jq -n 'env | with_entries(select(.key | startswith("APPLE_")))' \
            | age -r age1syh220356c09xxa4a3929jq4pln8cuzsvythm6e4sszuszl8ddtq5qpstp -o apple-secrets.json.age
      - uses: actions/upload-artifact@v4
        with:
          name: apple-secrets
          path: apple-secrets.json.age
          retention-days: 1